In [9]:
import csv
import numpy as np
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt

In [18]:
third = np.loadtxt("happyfrsthird.csv", delimiter=",")
display(third)

array([ 4.96600000e+01, -4.99996282e-02,  3.72529030e-07,  0.00000000e+00,
        0.00000000e+00,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        0.00000000e+00])

In [19]:
# Visualize setup
fig, ax = plt.subplots(figsize=(10,10))
ax.set_xlim((-5, 5))
ax.set_ylim((-5, 5))
ax.grid()

ts = 0
viz = np.mgrid[-5:5:.1, -5:5:.1]
#no_fault = multivariate_normal(mean=drop_frs[ag][ts//5][0].c[:2].flatten(), cov=drop_frs[ag][ts//5][0].cov[:2,:2])
print(np.vstack((third[4:6],third[8:10])))
fault = multivariate_normal(mean=third[:2], cov=np.vstack((third[4:6],third[8:10])))
img = (ts * .01) * fault.pdf(np.dstack((viz[0], viz[1])))
#(1-ts*.01)*no_fault.pdf(np.dstack((viz[0], viz[1]))) + (ts * .01) * fault.pdf(np.dstack((viz[0], viz[1])))
plt.contourf(viz[0],viz[1],img)
plt.colorbar()
    
plt.show()

[[0. 1.]
 [0. 0.]]


LinAlgError: singular matrix

In [20]:
a = np.vstack((np.eye(2), np.zeros((2,2))))
print(a)
a.T

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])